# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run code coverage

name: coverage

on:
  push:
    branches: [ main ]
    paths:
      - '**.js'
      - '**.jsx'
      - '**.json'
      - '**.html'
      - '**.css'
  pull_request:
    branches: [ main ]
    paths:
      - '**.js'
      - '**.jsx'
      - '**.json'
      - '**.html'
      - '**.css'

jobs:
  coverage:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - name: Run code coverage analysis
      run: npm run coverage
